default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: grep0lia
  pool: 5


development:
  <<: *default
  database: grepolia_development

test: &test
  <<: *default
  database: grepolia_testing

